### ISSUE TITLE
About pre-train checkpoints

### ISSUE THREAD

**Issue by onlyhantenghao** [zyhbili/Pose2Img#1]
Hi，what a great job！is it possible to release the pre-trained model of pose2img? and could this model generalize to custom person pictrue?

**Comment by zyhbili** [comment]
Thanks a lot! We are exhausted with ECCV now. And we will release the pre-trained model of Oliver in the next few weeks.
For custom person pictures, do you mean few-shot? Each model is trained on one person separately. Thus, it cannot generalize to the new person. If you want to animate another person, you need to train the model from scratch.

**Comment by onlyhantenghao** [comment]
> Thanks a lot! We are exhausted with ECCV now. And we will release the pre-trained model of Oliver in the next few weeks. For custom person pictures, do you mean few-shot? Each model is trained on one person separately. Thus, it cannot generalize to the new person. If you want to animate another person, you need to train the model from scratch.

Thanks for your reply and looking forward for the checkpoints.

**Comment by zyhbili** [comment]
> > Thanks a lot! We are exhausted with ECCV now. And we will release the pre-trained model of Oliver in the next few weeks. For custom person pictures, do you mean few-shot? Each model is trained on one person separately. Thus, it cannot generalize to the new person. If you want to animate another person, you need to train the model from scratch.
> 
> Thanks for your reply and looking forward for the checkpoints.

Demo checkpoint and dataset have been released. Please refer to README.md
