### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Ibrahimatef** [zyhbili/Pose2Img#2]
Thanks for your great work
Are there instructions or Readme file available to be followed to prepare dataset used to train the model?

**Comment by zyhbili** [comment]
> Thanks for your great work Are there instructions or Readme file available to be followed to prepare dataset used to train the model?

Demo dataset has been released. Please refer to README.md. 
For custom dataset, your only need to extract keypoints from images using OpenPose. And modified the config file.
If you have any other questions, feel free to contact me.

**Comment by Ibrahimatef** [comment]
Thanks For your response and updates,
To modify config file according to custom dataset, How are kp_var_root, mask_sigma_perp and root_node computed?

**Comment by zyhbili** [comment]
kp_var_root and mask_sigma_perp are hyperparam，i provide 'vis_hyperparams.py' as a tool to visualize them. In principal, the mask prior and keypoints gaussian maps should cover the correspondding parts.
root_node can be computed using https://github.com/zyhbili/Pose2Img/blob/850c913cb6239db67434e3377b48d91e18189e13/inference.py#L18
